# -*- coding: utf-8 -*-
"""Greetingapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CrG1ytuPm67BE74xu6OQKFNpyJTDKcwc
"""

import streamlit as st
st.title("اهلا بكم في موقعنا الاول باستخدام ستريم ليت")
name=st.text_input("ما هو اسمك")
if name:
  st.write("مرحبا بك يا",name)
  st.balloons()